### PR TITLE
MWPW-162943-Fix button text not visible issue on tab

### PR DESCRIPTION
**Pull request by Ruchika4**
- Fix button text not visible issue on tab

Resolves: [MWPW-162943](https://jira.corp.adobe.com/browse/MWPW-162943)

Test URLs:

Before: https://stage--cc--adobecom.hlx.page/products/photoshop/ai?unitylibs=stage
After: https://stage--cc--adobecom.hlx.page/products/photoshop/ai?unitylibs=MWPW-162943

### CODE REVIEW

**Review by sanjayms01 — APPROVED** [review]

**Review by robert-bogos — COMMENTED** [review]
The code looks good, but, using the before URL, the CTA text does not disappear on focus 🤔
It gets the `color: var(--color-black);` from [here](https://github.com/adobecom/unity/blob/stage/unitylibs/core/styles/styles.css#L49).

My question is if this is still an issue? so that we don't push a fix for a problem that does not exist.

**Comment by Ruchika4** [comment]
> The code looks good, but, using the before URL, the CTA text does not disappear on focus 🤔 It gets the `color: var(--color-black);` from [here](https://github.com/adobecom/unity/blob/stage/unitylibs/core/styles/styles.css#L49).
> 
> My question is if this is still an issue? so that we don't push a fix for a problem that does not exist.

Hi @robert-bogos , I am still able to reproduce the error
Screen Shot 2024-11-25 at 3 31 57 PM

**Comment by sigadamvenkata** [comment]
issue tested with give branch and now tabbing focused on button CTA and can see the CTA test as well. PFA
{85EC6FCC-E0F2-47DE-BAD7-9ECFD67352F8}

**Comment by robert-bogos** [comment]
@Ruchika4 
I am able to reproduce the error now. I was losing the `?unitylibs=stage` query parameter before, because of the microsoft login redirect.

**Review by robert-bogos — APPROVED** [review]

**Pull request merged**
