### PR TITLE
MWPW-160156 -Fix page loading issue on safari

### PR DESCRIPTION
**Pull request by Ruchika4**
fix issue of page with unity not loading on some versions of safari like 15, 16 etc.

Resolves: [MWPW-160156](https://jira.corp.adobe.com/browse/MWPW-160156)

Test URLs:

Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW160156

### CODE REVIEW

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by narcis-radu** [comment]
@Ruchika4 - I'm not convinced this is the way to go, we are diverging from Milo with this local `loadLinks` implementation. I see the `loadLink` code is working fine on Milo pages, why is there a problem with Unity? Would it be possible to adjust the code so that it uses `loadLink` or `loadScript` and `loadStyle` from Milo ?

**Comment by Ruchika4** [comment]
> https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=stage

Hi @narcis-radu , thanks for the review. Basically to fix the safari issue I am adding js file as a script tag in head instead of link. And I did thought of using loadScript function available in milo and that also resolves the issue because as mentioned above it adds the js file in a script tag in head. However it doesn't have an option to add async or defer in the script tag ([Milo Code](https://github.com/adobecom/milo/blob/ec48f3c105aef6f8b1682cbae35788ba099902ec/libs/utils/utils.js#L398)) hence loading of this script will block the page from rendering as per my understanding. And I was trying to avoid that for performance reasons. I can update milo loadScript function too to add async parameter if it is passed when calling loadScript function. Please let me know if that approach sounds better.

**Comment by narcis-radu** [comment]
@overmyheadandbody , @mokimo , @vhargrave , @robert-bogos - what do you think about @Ruchika4's suggestion? Would this be something that could be used by Milo / consumers or should we just isolate to Unity? Thanks!

**Comment by overmyheadandbody** [comment]
But Milo's `loadScript` could be called at the point you'd need it, right? So you wouldn't be blocking something from the beginning. The method resembles https://github.com/adobecom/milo/blob/ec48f3c105aef6f8b1682cbae35788ba099902ec/libs/utils/utils.js#L322 quite a lot. For consistency purposes, my vote would also be to make updates to that method, should they be needed in the first place. The power of Milo lies in easily sharing such utilities and keeping them in sync across consumers, breaking that pattern will likely lead to issues later on.

**Comment by mokimo** [comment]
+1 on @narcis-radu & @overmyheadandbody point to use milo native methods and checking if the milo method needs to be updated, if it faces the same page loading issues.

**Comment by Ruchika4** [comment]
> But Milo's `loadScript` could be called at the point you'd need it, right? So you wouldn't be blocking something from the beginning. The method resembles https://github.com/adobecom/milo/blob/ec48f3c105aef6f8b1682cbae35788ba099902ec/libs/utils/utils.js#L322 quite a lot. For consistency purposes, my vote would also be to make updates to that method or the one you references, should they be needed. The power of Milo lies in easily sharing such utilities and keeping them in sync across consumers, breaking that pattern will likely lead to issues later on.
> 
> As @narcis-radu mentioned, it is surprising that we haven't seen this issue in Milo. Is this a very recent issue that we should be checking on Milo pages as well? Could the culprit be somewhere else?

We are seeing the safari issue when we are are trying to convert the output of loadLink function in a promise and try to resolve it in Promise.all() for a js file. I am not aware if there is a similar use case in any other milo consuming site though

**Comment by Ruchika4** [comment]
I have updated the PR to use milo functions and have also raised a small PR to milo to update loadScript function here https://github.com/adobecom/unity/pull/131
Please review. Thanks

cc @narcis-radu  @mokimo  @overmyheadandbody

**Review by mokimo — APPROVED** [review]

**Review by sanjayms01 — APPROVED** [review]

**Review by robert-bogos — APPROVED** [review]
Thank you for addressing the feedback @Ruchika4 👍

**Pull request merged**
